def instructions():

    print('''
    1- You can move in straight lines only...
    2- It's not allowed to move right of left...
    3- You only have 3 lives...
    4- Type 'Instructions' to show the instructions again...
    ''')

instructions()